---
title: "first_lesson"
author: "Matteo Biglioli"
date: "5/24/2021"
header-includes:
  - \usepackage{subfig}
output:
  pdf_document: default
  html_document: default
---
```{r, include=FALSE, message=FALSE}
library(ggplot2)        # Basic plots
library(gridExtra)      # Multiple plot same figure
#library(cvms)           # Confusion Matrix
library(dplyr)          # Play w/ dataframes
library(broom)          # tidy()
library(GoodmanKruskal) # nice Corr Matrix
library(Hmisc)          # compute rcorr between quantitative vars
library(corrplot)       # plot nice corr matrix

###################################################################
# SMOTE stuff
library(ROCR)
install.packages("../libraries/DMwR_0.4.1.tar",repos=NULL, type="source")
library(DMwR)
###################################################################

# Set current directory as WD
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

source("../utils/plots.R")
source("../utils/data_analysis.R")
```

```{r}
dataset = read.csv("stroke.csv")
str(dataset)
```
```{r, warning=FALSE}
dataset$id = NULL

dataset$gender = factor(dataset$gender)
dataset$hypertension = factor(dataset$hypertension, levels = c(0,1), labels = c("No", "Yes"))
dataset$heart_disease = factor(dataset$heart_disease, levels = c(0,1), labels = c("No", "Yes"))
dataset$ever_married = factor(dataset$ever_married)
dataset$work_type = factor(dataset$work_type)
dataset$residence_type = factor(dataset$Residence_type)
dataset$Residence_type = NULL
dataset$smoking_status = factor(dataset$smoking_status)
dataset$stroke = factor(dataset$stroke, levels = c(0,1), labels = c("No", "Yes"))
dataset$bmi = as.numeric(dataset$bmi)

dataset = na.omit(dataset)
```
```{r}
str(dataset)
```

```{r, warning=FALSE, fig.width=10}
grid.arrange(ggplot(dataset, aes(x=stroke ,y=age)) +
              geom_boxplot(fill= "#FDE725FF", alpha= 0.7), 
            ggplot(dataset, aes(x=stroke, y=bmi))+
              geom_boxplot(fill= "#2D708EFF", alpha= 0.7), 
            ggplot(dataset, aes(x=stroke, y=avg_glucose_level))+
              geom_boxplot(fill= "#440154FF", alpha= 0.7), 
            ncol=3)
```

```{r, warning=FALSE, fig.width=10, fig.height=7, fig.align='center'}
source("../utils/plots.R")
#,fig.height=12

grid.arrange(factors_plot(tidy(table(dataset %>% select(stroke,work_type))), palette='Blues',
                         font_count_size=4, font_normalized_size=5.1, font_percentages_size=2.5,
                         font_categories_size=10), 
            factors_plot(tidy(table(dataset %>% select(stroke,smoking_status))), palette='Greens',
                         font_count_size=4, font_normalized_size=5.1, font_percentages_size=2.5,
                         font_categories_size=10),
            factors_plot(tidy(table(dataset %>% select(stroke,smoking_status))), palette='Purples',
                         font_count_size=4, font_normalized_size=5.1, font_percentages_size=2.5,
                         font_categories_size=10),
            ncol=3, nrow=1)
```
```{r, warning=FALSE, fig.width=10, fig.height=5, fig.align='center'}
grid.arrange(factors_plot(tidy(table(dataset %>% select(stroke,hypertension))), palette='Greens',
                         font_count_size=4.5, font_normalized_size=6, font_percentages_size=3.5,
                         font_categories_size=10), 
            factors_plot(tidy(table(dataset %>% select(stroke,heart_disease))), palette='Blues',
                         font_count_size=4.5, font_normalized_size=6, font_percentages_size=3.5,
                         font_categories_size=10), 
            factors_plot(tidy(table(dataset %>% select(stroke,residence_type))), palette='Purples',
                         font_count_size=4.5, font_normalized_size=6, font_percentages_size=3.5,
                         font_categories_size=10), 
            ncol=3, nrow=1)
```
```{r, warning=FALSE, fig.align='center'}
# qualitative corr
qualitative_vars = c('gender', 'hypertension', 'heart_disease', 'ever_married',
                      'work_type', 'smoking_status', 'residence_type')
plot(GKtauDataframe(dataset %>% select(all_of(qualitative_vars))))
```
```{r, fig.height=6, fig.width=5, fig.align='center'}
# TODO find a way to plot table and image side-by-side

quantitative_vars = c('age', 'avg_glucose_level', 'bmi')

corr <- rcorr(as.matrix(dataset %>% select(all_of(quantitative_vars))))

corrplot(corr$r, type = "upper", tl.col = "black", tl.srt = 45)

#flattenCorrMatrix(corr$r, corr$P)
```


```{r}
# TODO clean code and stuff

# data Preprocessing, Econding with OneHotEncoding ------------------------------
# 
# dummy <- dummyVars(" ~ gender + work_type + smoking_status + ever_married + Residence_type", data=stroke)
# newdata <- data.frame(predict(dummy, newdata = stroke))
# a <- stroke[,2:4]
# b <- stroke[,8:9]
# dt <- cbind(a, b, newdata, stroke['stroke'])
# dt <- as_tibble(dt)
# 
# y <- stroke['stroke']
```
 
```{r}
# Fill missing bmi data w/ tree prediction
# TODO keep this way? should we just remove them?
# 
# missing_index <-which(is.na(dataset$bmi))
# 
# train_set <- dataset[-c(missing_index),]
# 
# tree = caret::train(bmi ~ ., 
#                     data=train_set, 
#                     method="rpart", 
#                     trControl = trainControl(method = "cv"))
# predicted_bmi <- predict(tree, newdata = dataset[missing_index,])
# 
# #######################
# # What? Why?
# # x <- mean(bmi_pred)
# # bmi_pred[202] <- x
# #######################
# 
# dataset[missing_index,"bmi"] <- predicted_bmi
# 
# dataset = na.omit(dataset)
# 
# # Check quantitative correlation is under control w/ new data
# TODO side by side :)
# 
# new_corr <- rcorr(as.matrix(dataset %>% select(all_of(quantitative_vars))))
# flattenCorrMatrix(new_corr$r, new_corr$P)
# 
# grid.arrange(corrplot(corr$r,    type = "upper", tl.col = "black", tl.srt = 45), 
#             corrplot(new_corr$r, type = "upper", tl.col = "black", tl.srt = 45), 
#             ncol=2, nrow=1)

```
```{r}
# Solve the under sampling problem with SMOTE algho to create synth new data 

# dataset <- as.data.frame(lapply(dataset, as.factor)) # What? Why? 
# 
# trainSplit <- DMwR::SMOTE(stroke ~ ., dt, perc.over = 2000, perc.under=10)
# 
# dt_synth<- rbind(trainSplit,dt)
# 
# 
# dt_synth$work_type.Never_worked <- NULL # Again, but why :D
# 
# dt_synth$avg_glucose_level <- as.numeric(dt_synth$avg_glucose_level)
# dt_synth$bmi <- as.numeric(dt_synth$bmi)
# dt_synth$age <- as.numeric(dt_synth$age)

# TODO Show some stats of new dataset
```
```{r}
 # TODO recheck correlations, maybe w/ function to plot both side-by-side
```
```{r}
 # TODO add models/predictions
```